[tool.black]
line-length = 100
target-version = ['py311']
skip-string-normalization = true

[tool.isort]
profile = "black"
line_length = 100
known_first_party = ["core", "gui", "services", "resolvers", "audit"]
